package in.co.exception;

public class NewTryCatch {
public static void main(String[] args) {
	try {
		
	} catch (ArithmeticException e) {
		// TODO: handle exception
	}
	catch (NullPointerException e) {
		// TODO: handle exception
	}
	catch (RuntimeException e) {
		// TODO: handle exception
	}
	catch (Exception e) {
		// TODO: handle exception
	}
}

}
